config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_scope :user do
    authenticated do
      root 'users#index'
    end
    root 'users/registrations#new', as: :welcome
    get 'users/communities' => 'users/registrations#communities', as: :edit_communities
  end
  resources :posts, only: [:index]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/community.rb
class Community < ActiveRecord::Base
	TYPES = %w( Employer Gender Hometown Location Orientation Religion School )

	has_many :community_users
	has_many :users, through: :community_users
end

app/models/community_types/city.rb
class City < Community
end

app/models/community_types/employer.rb
class Employer < Community
end

app/models/community_types/gender.rb
class Gender < Community
end

app/models/community_types/hometown.rb
class Hometown < Community
end

app/models/community_types/location.rb
class Location < Community
end

app/models/community_types/orientation.rb
class Orientation < Community
end

app/models/community_types/religion.rb
class Religion < Community
end

app/models/community_types/school.rb
class School < Community
end

app/models/community_user.rb
class CommunityUser < ActiveRecord::Base
  belongs_to :community, polymorphic: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :community_users
  has_many :communities, through: :community_users, source_type: Community

  Community::TYPES.each do |community_type|
    has_many community_type.downcase.pluralize.to_sym, -> { where(type: community_type).order(:name) },
      through: :community_users, source: :community, source_type: Community
  end

  %w( Hometown Location ).each do |community_type|
    define_method "#{community_type.downcase}_ids" do
      self.send(community_type.downcase.pluralize).map(&:city_id)
    end

    define_method "#{community_type.downcase}_ids=" do |ids|
      cities = []
      Array(ids).reject(&:blank?).each do |id|
        city = City.find(id)
        hash = city.attributes.except("id", "type", "created_at", "updated_at").merge("city_id" => city.id)
        place = community_type.constantize.create_with(hash).find_or_create_by(city_id: id)
        cities << place
      end
      update(community_type.downcase.pluralize => cities)
    end
  end

  def communities_shared_with(user)
    communities & user.communities
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def create
    # Auto-generate temporary password
    generated_password = Devise.friendly_token.first(10)
    params[:user][:password] = generated_password
    super
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end

  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    Community::TYPES.each do |community_type|
      devise_parameter_sanitizer.for(:account_update) << { "#{community_type.downcase}_ids" => [] }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.select('users.*, COUNT(DISTINCT communities.id) AS community_count')
    @users = @users.preload(:communities).joins(:communities).where(communities: { id: current_user.community_ids })
    @users = @users.where.not(id: current_user)
    @users = @users.where("users.name <> ''")
    @users = @users.group('users.id')
    @users = @users.having('COUNT(DISTINCT communities.id) > 1')
    @users = @users.order('community_count DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.header
	.logo
		= link_to root_path do
			| thirdplace
	.menu
		li class=('active' if current_page? root_path)
			= link_to root_path do
				span.octicon.octicon-organization
		li
			= link_to posts_path do
				span.octicon.octicon-rss
		li
			= link_to root_path do
				span.octicon.octicon-comment-discussion
		li class=('active' if current_page? edit_communities_path)
			= link_to edit_communities_path do
				span.octicon.octicon-gear

app/views/layouts/application.html.slim
doctype html
html
	head
		meta charset='utf-8'
		meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'
		title thirdplace
		meta content='' name='description'
		meta content='width=device-width' name='viewport'
		= stylesheet_link_tag 'application', media: 'all'
		== yield :stylesheet
		= javascript_include_tag '//use.typekit.com/ier1ulg.js'
		= javascript_tag 'try{Typekit.load()}catch(e){}'
		= csrf_meta_tags
	body
		== yield
		= javascript_include_tag 'application'
		== yield :javascript
		= debug(params) if Rails.env.development?

app/views/users/_user.html.slim
.user
	.user-image
		= image_tag "http://graph.facebook.com/3017#{rand(1..100)}/picture?type=large"
	.user-name
		= user.name.split(" ").first
	.user-communities
		- user.communities_shared_with(current_user).each do |community|
			= link_to root_path do
				span.octicon.octicon-globe
				= community.name
	.user-actions
		= link_to root_path do
			span.octicon.octicon-check
		= link_to root_path do
			span.octicon.octicon-x

app/views/users/index.html.slim
.container
	= render 'layouts/header'
	= render @users